name: app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_modular: ^1.2.7+1
  build_context:
  shared_preferences: ^0.5.7+3
  mobx: ^1.2.1+1
  flutter_mobx:
  firebase_auth: ^0.15.2
  google_sign_in: ^4.1.0
  freezed_annotation:
  dartz:
  uuid:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen:
  freezed:

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
